spring:
  application:
    name: gmall-search

  # Nacos Config
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

# Server HTTP
server:
  port: 16000

logging:
  level:
    org.sirius.gmall.search: debug
